In [16]:
def tick_bars(raw_data, num_ticks=1000):
    '''
    :param raw_data: time bars
    :return: tick bars
    '''
    #inds = range(0, 10000, 1000)
    inds = range(0, raw_data.shape[0], num_ticks)
    tbs = raw_data.loc[inds]
    return tbs

import pandas as pd

raw_file = "IVE_tickbidask.txt"
cols = ['date','time','price','bid','ask','size']
raw_data = (pd.read_csv(raw_file,nrows=5000,header=None)
            .rename(columns=dict(zip(range(len(cols)),cols))))
raw_data.head()
tick_bars(raw_data)

            date      time  price    bid    ask  size
0     09/28/2009  09:30:00  50.79  50.70  50.79   100
1000  09/28/2009  11:22:56  51.35  51.35  51.36   100
2000  09/28/2009  14:18:52  51.47  51.47  51.48   100
3000  09/29/2009  10:03:18  51.52  51.51  51.52  1679
4000  09/29/2009  11:53:20  51.47  51.46  51.48   100